src/HtmlServiceProvider.php

The ServiceProvider is deferred, thus only runs when something listed in `provides()` is requested. But when you use dependancy injection, the alias is used.
This adds those aliases. Fixes problems with TwigBridge (https://github.com/rcrowe/TwigBridge/issues/194, https://github.com/rcrowe/TwigBridge/issues/150, https://github.com/rcrowe/TwigBridge/issues/156, https://github.com/rcrowe/TwigBridge/pull/184)
(If you test, remember that `php artisan clear-compiled` is needed before changes are reflected in the app)

Add aliases to provides()

---

src/FormBuilder.php
tests/FormBuilderTest.php

This patch modifies the placeholder option setting its value to empty, so empty data is passed for dropdown. #60
Currently the placeholder values is being passed which it could be a problem.
Perhaps placeholder option should accept an array or a string in order to allow placeholder value to be specified explicitly.
Feedback is appreciated.

Modify Placeholder to not send data

---

src/FormBuilder.php

HOW TO REPRODUCE BUG:
I have an m:m relation in my isolated form.
This relation si rendered by a list of checkboxes.
Checkboxes names are in the form form_name[relation_name][]
BUG:
Form checkboxes autofill functionalities works well only when:
1. On new form (method=get)
2. On posting some errors
ERROR:
On edit form data the autofill functionalities wont' work because $posted is a Collection, so my edit.

FIX on FromBuilder.php

---

src/FormBuilder.php
tests/FormBuilderTest.php

This an important missing feature in this package. There were several pull requests these weeks : #18 and #40. I think that the first one is not in compliance with the *fluent* Laravel style. The second one is close to a good solution but it miss unit testing and a proper code formatting.
For the anecdote, I have made a similar pull request (https://github.com/laravel/framework/pull/3021) long time ago that was merged in the 4.0 branch but lost in master !
I have kept the work of @pazzoone except for this things :
- I removed the dependency to `Illuminate\Database\Eloquent\Collection`, because it is not a dependency of this package.
- I passed the second parameter to the `getValueAttribute` method in order to to be able to set a custom default value.
And, of course, I added a unit test …

Checkboxes work with relationships

---

src/HtmlBuilder.php

Methods listingElement and nestedListing are documented as receiving a string as third parameters ($value).
However :
1) first instruction in listingElement method is testing if $value is an array
2) if $value is an array, listingElement calls nestedListing element with $value as third parameter (which then is an array).
I have choosed to change the parameter type in docbloc for both methods from string to mixed as $value can also be integer, float, object with __toString method...
Issue in scrutinizer : https://scrutinizer-ci.com/g/simondubois/budget/issues/master/files/app/Services/Html/HtmlBuilder.php?orderField=path&order=asc

Fix incorrect param type in HtmlBuilder codeblock

---

src/FormBuilder.php

`html->attributes()` already does the escaping.
Let us not depend on the double escaping protection mechanism of `htmlentities()`.
This PR is a copy of https://github.com/illuminate/html/pull/18.

Don't double escape in Form::option()

---

tests/HtmlBuilderTest.php

Mockery is not used in HtmlBuilderTest, use statement and tear down should be removed.

Remove dead code in HtmlBuilderTest

---

src/HtmlServiceProvider.php

`bindShared()` will be deprecated in laravel 5.2 in favour of `singleton()`
http://laravel.com/docs/5.1/upgrade#upgrade-5.1.0 under Deprecations

Replace bindShared with singleton

---

src/FormBuilder.php

Don't depend on concretes in FormBuilder

---

src/HtmlBuilder.php

HtmlBuilder is now coupled to the concrete UrlGenerator which makes it impossible to swap out Laravel's routing component. 
By depending on the interface (contract) this issue will be fixed.

HtmlBuilder shouldn't depend on concrete implementation

---

src/Componentable.php

This allows for using boolean values as default options for components.

Use array_get's third parameter for default value.

---

tests/FormBuilderTest.php

There isn't a test for selects that have optgroups, so I added a basic test for it.

Add test for select optgroups

---

.travis.yml

PHP 7 is the current supported PHP version, it is important to show and validate that this package is compatible :)
I'm making one pull request per branch to simplify the merging task.

Add PHP 7 to travis configuration

---

src/FormBuilder.php

As said in #149:
If two forms are loaded with different methods, they load fine the first time.
If the page is redirected back, the second form will load the first form _method, which is a problem.
This commit changes this to not load old attribute if the object is "_method".

Avoid using session to build form

---

src/FormBuilder.php
tests/FormBuilderTest.php

I run into this issue when I was creating a checkbox with a label that should contain a link to an agreement page. I'd like to make html escaping optional for all labels. 
Besides the added feature I think it's also an improvement because we're using $this->html->entities instead of e() to escape the value.
#167 Also reported this as an issue.

Html escaping is now optional for labels

---

src/FormBuilder.php
src/HtmlBuilder.php
src/helpers.php
tests/FormAccessibleTest.php
tests/FormBuilderTest.php
tests/HtmlBuilderTest.php

Similar to @StefanPrintezis's request #174, this makes the entities() escaping of HTML link labels optional.  Allows for using this lib for creating (trusted/internal) links around HTML elements (<i>, <img>, <span>, etc).

Make escaping of labels for HTML and mailto links optional

---

src/Eloquent/FormAccessible.php
src/FormBuilder.php
tests/FormAccessibleTest.php

When a model is using the FormAccessible trait, it is unable to get the value from related model.
Here is the example of the code, where address is the related model
`{{ Form::text('address[street1]', null, ['class' => 'form-control']) }}`

Getting form value from related model

---

src/FormBuilder.php

Currently, the form model accessor does not work on multi value fields such as "field[]". This pull request fixes it.

Transform the field name when getting the form value from model

---

src/FormBuilder.php
src/HtmlBuilder.php
tests/FormBuilderTest.php
tests/HtmlBuilderTest.php

I've replaced e with htmlentities().
#254 Reported this as an issue.

Values are now encoded consistently by the formbuilder and the htmlbuilder

---

src/HtmlBuilder.php
tests/HtmlBuilderTest.php

HTML properties shouldn't have value. Attributes with boolean values will now be represented as HTML properties.
Given this Blade snippet:
``` blade
{!! Form::text('timezone', null, ['class' => 'form-control', 'placeholder' => 'Timezone', 'my-property' => true]); !!}
```
It will compile to:
``` html
<input class="form-control" placeholder="Timezone" my-property name="timezone" type="text" id="timezone">
```

Treat boolean attributes as HTML properties

---

src/FormBuilder.php
tests/FormAccessibleTest.php

`Collective\Html\HtmlBuilder::getModelValueAttribute` currently does not mutate attributes on the related models.
By calling it recursively, it would allow mutating the form attributes in the related models.

Mutating form attributes in related models

---

src/FormBuilder.php
tests/FormBuilderTest.php

It's the second try to add support for custom attributes in `option` tag. The PR is inspired by https://github.com/LaravelCollective/html/pull/129 and @mlantz comments.

[5.4] Allow select options to have attributes

---

tests/FormAccessibleTest.php

I actually tried to patch this 'bug' (which was still present on the last released version 5.2.4), but after writing these tests realized that they have already been fixed on this branch. For what it's worth I'm not really sure if the tests add anything or if I actually wrote them properly (since they didn't fail), but more unit tests are always better, right?

Add unit tests for #190 and #191 (FormAccessor trait being inconsistent when used with getters and key transformation)

---

src/FormBuilder.php

`getSelectedValue` returns always true if it receives a value (from an select input) of 0. To avoid that the strict parameter has to be set to true.
This is because the following code does not work as might expected:
```
<?php
// check if 0 is in the array [1 => "c16"]
var_dump(in_array(0, [1=>"c16"])); // returns true
```
Setting the strict parameter to true allows to include options with a value of 0 (zero).

Update FormBuilder.php: fix to get selected value with 0 as index

---

tests/FormBuilderTest.php

Added assertion for the case, that the options for the select field contain a zero key, eg `['0' => 'All Sizes', 'L' => 'Large']`
See also commit: https://github.com/LaravelCollective/html/pull/127/commits

FormBuilderTest: testSelect: added test for '0'-key option

---

src/FormBuilder.php
tests/FormBuilderTest.php

If `email`, `tel` and `number` are all included, shouldn't we let `search` join the party too

FormBuilder.php: Added search() method

---

src/FormBuilder.php
src/HtmlBuilder.php

For 5.2 and later branches. Fixes #241.
Refs https://github.com/LaravelCollective/html/commit/4c9b44a817543bd0ef7f0ca8c8a63e5556504274.

Check if component/macro exists instead of relying on exceptions

---

src/FormBuilder.php

Fixes https://github.com/LaravelCollective/html/issues/347
**Background** 
This PR essentially reverts this PR: https://github.com/LaravelCollective/html/commit/410943c5e19fbdee374d1ed9c59a43b2a365e66d changes the way the placeholder value behaves in the select (dropdown) input.
**Changes**  
- Removes disabled and hidden options on placeholder
**To Verify**    
- checkout branch `git checkout <branch-name>`
- verify placeholder is selectable

Dont enforce disabled/hidden placeholder

---

src/FormBuilder.php

E.G. when you submit a form with a `PATCH` method and then you submit another form which use a `DELETE` method instead, the [`FormBuilder::getValueAttribute()`](https://github.com/LaravelCollective/html/blob/v5.4.8/src/FormBuilder.php#L1137) method use the previous value of the hidden input `_method` attribute.
So the value is replaced by `PATCH` instead of the desired `DELETE` value.
Maybe related to https://github.com/LaravelCollective/html/issues/350#issuecomment-309899542
PS: I use AJAX/XHR to submit my forms.
So I don't have any HTTP redirection between my two forms submit, just DOM replacements on the Browser

Form method of hidden input '_method' is preserved on next request

---

src/FormBuilder.php
tests/FormBuilderTest.php

Initially I proposed making this optional but PR was merged without discussion about that.
So I make `Request` optional and you need `Form::considerRequest(true)` for enable it.
https://github.com/LaravelCollective/html/issues/369
https://github.com/LaravelCollective/html/issues/375

Make Request Optional

---

src/HtmlBuilder.php

As stated in #265 
I didn't change the name of the function, because it still creates html entities.

[5.4] Replaced htmlentites() with htmlspecialchars()

---

src/Eloquent/FormAccessible.php
src/FormBuilder.php
src/HtmlBuilder.php
tests/FormBuilderTest.php

Addresses the concerns in #129. This PR does the following:
1. Adds a new $optgroupsAttributes parameter to the _select_ method which is used to add attributes to optgroups. Previously attributes applied to a an array element that was an optgroup would apply the attributes to every option belonging to the optgroup (rather than the optgroup itself).
2. Increases the depth of $optionsAttributes by 1. To add attributes to options inside an optgroup, use the optgroup name as the key with an array of options and their attributes as the value. Previously there was no way to add attributes to options belonging to an optgroup individually.
See the formBuilderTest changes for an example implementation.

Added $optgroupsAttributes parameter to select method.

---

src/FormBuilder.php

_FYI: This pull request was already merged in the [5.4](https://github.com/LaravelCollective/html/tree/5.4) branch but not in the [5.5](https://github.com/LaravelCollective/html/tree/5.5) branch_
E.G. when you submit a form with a `PATCH` method and then you submit another form which use a `DELETE` method instead, the [`FormBuilder::getValueAttribute()`](https://github.com/LaravelCollective/html/blob/v5.5.1/src/FormBuilder.php#L1135) method use the previous value of the hidden input `_method` attribute.
So the value is replaced by `PATCH` instead of the desired `DELETE` value.
Maybe related to https://github.com/LaravelCollective/html/issues/350#issuecomment-309899542
PS: I use AJAX/XHR to submit my forms.
So I don't have any HTTP redirection between my two forms submit, just DOM …

[5.5] Form method of hidden input '_method' is preserved on next request

---

src/HtmlBuilder.php
tests/HtmlBuilderTest.php

Currently, `link()` fails to escape HTML entities in the URL provided. 
Example: Given the URL `https://a.com/b?id=4&not_id=5`, `link()` produces the following HTML:
```html
<a href="https://a.com/b?id=4&not_id=5">URL which needs escaping</a>
```
Chrome and Safari both interpret the URL as `https://a.com/b?id=4¬_id=5`, which is clearly not intended.
(Resubmitting of #420 to master.)

Proposal: Escape HTML entities in `src`-attribute

---

composer.json
src/Eloquent/FormAccessible.php
src/FormBuilder.php
src/HtmlBuilder.php
tests/FormBuilderTest.php
tests/HtmlBuilderTest.php

When adding the FormAccessible trait to a model, the getFormValue method treats some inputs like nestedModel wrongly!
Because of it some checkboxes came unchecked.

Fix some inputs treated like nestedModel when using an accessor

---

src/FormBuilder.php
tests/FormBuilderTest.php

Placeholder still show when generate `Form::select(...)`
```
{!! Form::select('test_id', ['test1'=>'test1', 'test2'=>'test2'], null, ['placeholder' => 'Test select']) !!}
```

Fix placeholder not hide in select list.

---

.travis.yml
composer.json
src/FormBuilder.php
src/HtmlBuilder.php

Support for 5.6, tests do pass.
While checking the tests I found a bug, where the `$optGroupAttributes` wheren't added to the optgroup but where added to the child options, instead of their respective attributes. (The bug came up with the changes made in #470)
I'd like to mention that I opted out double encoding (it is now default in the `e` helper function in 5.6, so that this package works like before. If this package should, from now on, use double encoding by default I'm happy to revert the changes and fix the tests instead.

Added Laravel 5.6 stable support

---

.travis.yml
composer.json
src/FormBuilder.php

_FYI: This pull request was already merged in the [5.4](https://github.com/LaravelCollective/html/tree/5.4) branch but not in the [master](https://github.com/LaravelCollective/html/tree/master) branch_
E.G. when you submit a form with a `PATCH` method and then you submit another form which use a `DELETE` method instead, the [`FormBuilder::getValueAttribute()`](https://github.com/LaravelCollective/html/blob/f905913a3ab7ca639b69138aab28baa01d400034/src/FormBuilder.php#L1135) method use the previous value of the hidden input `_method` attribute.
So the value is replaced by `PATCH` instead of the desired `DELETE` value.
Maybe related to https://github.com/LaravelCollective/html/issues/350#issuecomment-309899542
PS: I use AJAX/XHR to submit my forms.
So I don't have any HTTP redirection …

[5.6] Form method of hidden input '_method' is preserved on next request

---

src/FormBuilder.php
tests/FormBuilderTest.php

Validation for this situation: selected value is a boolean in select field
Method: [FormBuilder::getSelectedValue($value, $selected)](https://github.com/AndersonFriaca/html/blob/8e96ea08a37a6db542de7234270898bdfea0045f/src/FormBuilder.php#L783)
Example:
```php
$avc = true;
{{Form::select('avc', [1 => 'Yes', 0 => 'No'], $avc, ['placeholder' => 'Select'])}}
```

Possibility of boolean value for selected option in select field

---

src/FormBuilder.php
tests/FormBuilderTest.php

Validation for this situation: selected value is a boolean in select field
Method: [FormBuilder::getSelectedValue($value, $selected)](https://github.com/AndersonFriaca/html/blob/8e96ea08a37a6db542de7234270898bdfea0045f/src/FormBuilder.php#L783)
Example:
```php
$avc = true;
{{Form::select('avc', [1 => 'Yes', 0 => 'No'], $avc, ['placeholder' => 'Select'])}}
```
**_The pull request for master is [here](https://github.com/LaravelCollective/html/pull/487) and was merged_**
_Please publish a new release with these changes_

[5.6] Validation in select field for boolean value of selected option

---

src/FormBuilder.php
tests/FormBuilderTest.php

Validation for this situation: selected value is a boolean in select field
Method: [FormBuilder::getSelectedValue($value, $selected)](https://github.com/AndersonFriaca/html/blob/8e96ea08a37a6db542de7234270898bdfea0045f/src/FormBuilder.php#L783)
Example:
```php
$avc = true;
{{Form::select('avc', [1 => 'Yes', 0 => 'No'], $avc, ['placeholder' => 'Select'])}}
```
**_The pull request for master is [here](https://github.com/LaravelCollective/html/pull/487) and was merged_**

[5.5] Validation in select field for boolean value of selected option

---

src/FormBuilder.php
tests/FormBuilderTest.php

Fixes: https://github.com/LaravelCollective/html/issues/496
Loose comparison needs to be done because Laravel model casting may be in affect and therefore 1 == true and 0 == false.

Fixed bug with radio button not being checked

---

src/FormBuilder.php

_FYI: This fix was merged in the pull request https://github.com/LaravelCollective/html/pull/460
But the pull request https://github.com/LaravelCollective/html/pull/471 accidentally revert this fix_ 😕
E.G. when you submit a form with a `PATCH` method and then you submit another form which use a `DELETE` method instead, the [`FormBuilder::getValueAttribute()`](https://github.com/LaravelCollective/html/blob/v5.5.1/src/FormBuilder.php#L1135) method use the previous value of the hidden input `_method` attribute.
So the value is replaced by `PATCH` instead of the desired `DELETE` value.
Maybe related to https://github.com/LaravelCollective/html/issues/350#issuecomment-309899542
PS: I use AJAX/XHR to submit my forms.
So I don't have any HTTP redirection between my two forms submit, just DOM …

[5.5] Fix form method of hidden input '_method' is preserved on next request

---

src/Componentable.php

renderComponent return a HTMLString (Illuminate\Support\HtmlString)

Wrong return doc comment in renderComponent function

---

src/FormBuilder.php

Hello !
For test my Web App Laravel 5.8, when I was doing (with the php version 7.2 ou 7.3) : php ./vendor/phpunit/phpunit/phpunit
I am this error in my log :
> testing.ERROR: count(): Parameter must be an array or an object that implements Countable...
PS : I have PHP 7.3 on my serveur LEMP.
I changed the line that posed this problem.
Thank you.

Laravel 5.8 - Add compatibility with >=7.2 for tests

---

src/HtmlServiceProvider.php

Followup for https://github.com/laravel/framework/pull/27505
`$defer` property has deprecated in 5.8 and has removed in 6.0

[6.0] Use DeferrableProvider interfaces instead of defer property

---

composer.json

Necessary to resolve the incompatibility now that Laravel 6.1 was tagged.

Update constraints to match Laravel 6 releases
