src/HtmlBuilder.php, tests/HtmlBuilderTest.php
Method generates a description list of items.
=> Proposal: add a dl method to HtmlBuilder

src/FormBuilder.php
No need to involve Carbon in the discussion.
=> Use DateTime

src/HtmlBuilder.php, tests/HtmlBuilderTest.php
Added a helper to create simple key–value pair meta tags. Also created a corresponding test.
=> Create meta helper

src/FormBuilder.php, tests/FormBuilderTest.php
This also fixes model-form binding with collections inside models.
=> Fix model form-binding with array with objects and object with arrays.

src/FormBuilder.php, tests/FormBuilderTest.php
Added time input as a new HTML 5 input
=> Add time input

src/FormBuilder.php, tests/FormBuilderTest.php
Added HTML5 tel input type for telephone numbers
=> Added tel input type and test

src/FormBuilder.php, tests/FormBuilderTest.php
This commits has been merged into 5.0 (thanks for that) but should also be merged into 5.1.
As @arthurkirkosa said in #45, a new release would be great.
=> [5.1] Checkboxes work with relationships

src/FormBuilder.php
Add convenience methods for creating `datetime` and `datetime-local` input types.
=> Add datetime input types

src/HtmlBuilder.php
One of the most useful features of the Definition List is multiple definitions per term. <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl>
=> dl() now supports multiple descriptions per term

src/HtmlBuilder.php, tests/HtmlBuilderTest.php
I added a function tag to allow creation of any kind of html tag to be used like:
Html::tag($tag, $content, array $attributes = []);
for example:
Html::tag('p', 'this is a paragraph', ['class' => 'text-center]);
generating:
<p class="text-center">this is a paragraph</p>
an array can be also passed as content:
Html::tag('div', ['<p>this is a paragraph</p>', '<p>this is another paragraph</p>'], ['class' => 'row]);
generating:
<div class="row">
<p>this is a paragraph</p>
<p>this is another paragraph</p>
</div>
Yo can use Html and Form facades in content array:
Html::tag('div', [Form::text('name'), ..., Form::text('n')], ['class' => 'row]);
=> Function Tag

src/HtmlServiceProvider.php
This fixes the breaking changes specified in #330.
=> Changed how Blade directives are registered to prevent conflicts

src/FormBuilder.php, tests/FormBuilderTest.php
http://stackoverflow.com/a/8442831/1722248
=> changed select placeholder to reflect major browser standards

src/FormBuilder.php, src/HtmlServiceProvider.php, tests/FormBuilderTest.php
I tried to implement what I want here https://github.com/LaravelCollective/html/issues/180
Shortly: adding support for fill value from Request in case you want autosave user input without redirect. Maybe useful for filter or search pages when you can't redirect user to show result and want filter params to be saved.
=> Fill values by current Request

src/HtmlServiceProvider.php
Fixes issue as described in https://github.com/LaravelCollective/html/issues/342
=> Fix for undefined function getToken() on Laravel 5.4

src/HtmlServiceProvider.php
This was fixed in your 5.4 branch but not in the master branch.
Will need it in master for laravel 5.5 compatibility.
Thanks.
/S
=> Fix getToken() for token().

composer.json
Add support for auto discovery.
=> Add branch alias for 5.5.x-dev.

src/FormBuilder.php
=> Moved PR#368 to 5.3 branch

src/FormBuilder.php
https://github.com/LaravelCollective/html/pull/368
=> Moved PR#368 to 5.1 branch

src/HtmlBuilder.php, tests/HtmlBuilderTest.php
=> Remove PHP_EOL statements by HTML-tags ..

src/FormBuilder.php
=> Use strict comparison to check selected values when building select options

src/FormBuilder.php, src/HtmlBuilder.php
for favicon and style methods in HtmlBuilder and also option method in FormBuilder.
=> + operator doesn't merge. Replaced by array_merge method.

src/FormBuilder.php
It would be nice to be able to get the model before setting a new one (maybe in a partial) and having the original model to set back at the end of the partial.
=> Adds getModel()

src/Eloquent/FormAccessible.php, tests/FormAccessibleTest.php
Fresh
https://github.com/LaravelCollective/html/pull/353
=> Getting data for a form from a relation

src/HtmlBuilder.php
Change the `style` function to chose `defaults` as the lower priority and `attributes` as the higher priority.
=> Fix the issue where defaults has a higher priority then the attributes

src/FormBuilder.php, tests/FormBuilderTest.php
Ways to use:
```
Form::datalist('genders', ['M' => 'Male', 'F' => 'Female']);
...
<datalist id="genders">
<option value="M">Male</option>
<option value="F">Female</option>
</datalist>
```
```
Form::datalist('genders', [5 => 'Male', 6 => 'Female']);
...
<datalist id="genders">
<option value="5">Male</option>
<option value="6">Female</option>
</datalist>
```
```
Form::datalist('genders', ['Male', 'Female']);
...
<datalist id="genders">
<option value="Male">Male</option>
<option value="Female">Female</option>
</datalist>
```
=> Create datalist form element

src/FormBuilder.php, tests/FormBuilderTest.php
Resubmit of https://github.com/LaravelCollective/html/pull/376 against actual branch.
=> Make Request optional

src/HtmlBuilder.php, tests/FormBuilderTest.php, tests/HtmlBuilderTest.php
In case of you want to add class by condition.
```
Form::text('name', null, ['class' => [
'form-control-,
$error ? 'is-invalid' : '',
]]);
```
=> Can set class attribute in array.

composer.json
=> Add support for Laravel 5.7

composer.json, readme.md, src/Componentable.php, src/FormBuilder.php
Remvoe Laravel deprecated helper function and use Arr and Str Facade instead. 
Update composer.json for Laravel 5.8
=> Pull request for Larvel 5.8

src/HtmlBuilder.php
Closes https://github.com/LaravelCollective/html/issues/575
=> Change order in array_merge

readme.md
=> update link for docs
